export const enum ApplicationRoutes {
  Empty = '',
  Dashboard = 'dashboard',
  Settings = 'settings',
  SystemSetup = 'system-setup',
  CustomerService = 'customer-service',
  InsuranceRenewals = 'insurance-renewals',
  ProductManagement = 'product-management',
  TreatyManagement = 'treaty-management',
  GeneralInsuranceUnderwriting = 'general-insurance-underwriting',
  LifeInsuranceUnderwriting = 'life-insurance-underwriting',
  MedicalInsuranceUnderwriting = 'medical-insurance-underwriting',
  MotorInsuranceUnderwriting = 'motor-insurance-underwriting',
  Payroll = 'payroll',
  AccountsPayable = 'accounts-payable',
  Cashier = 'cashier',
  FinanceAndReporting = 'finance-and-reporting',
  GeneralAccounting = 'general-accounting',
  ActivityLog = 'activity-log',
  CorrespondenceManagement = 'correspondence-management',
}
