export enum ElementsTypes {
  Link = 0,
  DynamicLink = 1,
  Check = 2,
  Select = 3,
  Table = 4,
  Attachment = 5,
  Ein = 6,
  Text = 7,
  Script = 8,
  TextEditor = 9,
  Date = 10,
  DateAndTime = 11,
  Number = 12,
  String = 13,
  Barcode = 14,
  Button = 15,
  Color = 16,
  Currency = 17,
  Json = 18
}
