import { NgModule } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

@NgModule({
  declarations: [],
  exports: [],
})
export class IconSvgModule {
  constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    iconRegistry
      .addSvgIcon(
        /** Usage <mat-icon svgIcon="bed" color="primary"></mat-icon> **/
        'logo',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/logo.svg'
        )
      )
      .addSvgIcon(
        'notification',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/notification.svg'
        )
      )
      .addSvgIcon(
        'menu',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/menu.svg'
        )
      )
      .addSvgIcon(
        'close',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/close.svg'
        )
      )
      .addSvgIcon(
        'chat',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/chat.svg'
        )
      )
      .addSvgIcon(
        'small-down',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/small-down.svg'
        )
      )
      .addSvgIcon(
        'user-profile',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/user-profile.svg'
        )
      )
      .addSvgIcon(
        'language',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/language.svg'
        )
      )
      .addSvgIcon(
        'logout',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/logout.svg'
        )
      )
      .addSvgIcon(
        'search',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/search.svg'
        )
      )
      .addSvgIcon(
        'treaty',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/treaty.svg'
        )
      )
      .addSvgIcon(
        'report-viewer',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/report-viewer.svg'
        )
      )
      .addSvgIcon(
        'system-setup',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/system-setup.svg'
        )
      )
      .addSvgIcon(
        'settings',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/settings.svg'
        )
      )
      .addSvgIcon(
        'entity-management',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/entity-management.svg'
        )
      )
      .addSvgIcon(
        'search-gray',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/search-gray.svg'
        )
      )
      .addSvgIcon(
        'product-management',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/product-management.svg'
        )
      )
      .addSvgIcon(
        'activityLog',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/activityLog.svg'
        )
      )
      .addSvgIcon(
        'correspondence',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/correspondence.svg'
        )
      )
      .addSvgIcon(
        'customer-service',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/customer-service.svg'
        )
      )
      .addSvgIcon(
        'insurance-underwriting',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/insurance-underwriting.svg'
        )
      )
      .addSvgIcon(
        'accounting-and-finance',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/accounting-and-finance.svg'
        )
      )
      .addSvgIcon(
        'dashboard',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/dashboard.svg'
        )
      )
      .addSvgIcon(
        'microphone',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/microphone.svg'
        )
      )
      .addSvgIcon(
        'attach',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/attach.svg'
        )
      )
      .addSvgIcon(
        'call-out',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/call-out.svg'
        )
      )
      .addSvgIcon(
        'gallery',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/gallery.svg'
        )
      )
      .addSvgIcon(
        'human-resources',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/human-resources.svg'
        )
      )
      .addSvgIcon(
        'back',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/back.svg'
        )
      )
      .addSvgIcon(
        'true',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/true.svg'
        )
      )
      .addSvgIcon(
        'false',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/false.svg'
        )
      )
      .addSvgIcon(
        'add-grid',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/add-grid.svg'
        )
      )
      .addSvgIcon(
        'customer-contact-form-paperclip',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/paperclip.svg'
        )
      )
      .addSvgIcon(
        'customer-contact-form-mail',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/mail.svg'
        )
      )
      .addSvgIcon(
        'customer-contact-form-call',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/call.svg'
        )
      )
      .addSvgIcon(
        'customer-contact-form-gallery',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/gallery.svg'
        )
      )
      .addSvgIcon(
        'customer-contact-form-audio',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/audio.svg'
        )
      )
      .addSvgIcon(
        'customer-service-happy-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/happy-svgrepo-c.svg'
        )
      )
      .addSvgIcon(
        'customer-service-happy-nocolor-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/happy-nocolor.svg'
        )
      )
      .addSvgIcon(
        'customer-service-sad-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/sad.svg'
        )
      )
      .addSvgIcon(
        'customer-service-sad-nocolor-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/sad-nocolor.svg'
        )
      )
      .addSvgIcon(
        'customer-service-sad-1-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/sad-1.svg'
        )
      )
      .addSvgIcon(
        'customer-service-sad-nocolor-1-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/sad-nocolor-1.svg'
        )
      )
      .addSvgIcon(
        'customer-service-arrow-down-notes',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/arrow-down(notes).svg'
        )
      )
      .addSvgIcon(
        'customer-service-arrow-up-notes',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/arrow-up(notes).svg'
        )
      )
      .addSvgIcon(
        'customer-service-calculator',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/calculator.svg'
        )
      )
      .addSvgIcon(
        'customer-service-assentify',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/assentify.svg'
        )
      )
      .addSvgIcon(
        'customer-service-select-down',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/select-down.svg'
        )
      )
      .addSvgIcon(
        'customer-service-full-sad',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/sad-svgrepo-com (1).svg'
        )
      )
      .addSvgIcon(
        'customer-service-delete-history',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/delete.svg'
        )
      )
      .addSvgIcon(
        'customer-service-lock-history',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/customer-service-icons/lock-svgrepo-co.svg'
        )
      )
      .addSvgIcon(
        'policy-filter',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/policy-svg-icons/filter.svg'
        )
      )
      .addSvgIcon(
        'policy-box',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/policy-svg-icons/box.svg'
        )
      )
      .addSvgIcon(
        'policy-phone',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/policy-svg-icons/phone.svg'
        )
      )
      .addSvgIcon(
        'policy-alert',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/policy-svg-icons/alert.svg'
        )
      )
      .addSvgIcon(
        'policy-calculator',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/policy-svg-icons/calculator.svg'
        )
      )
      .addSvgIcon(
        'copy-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/copy-icon.svg'
        )
      )
      .addSvgIcon(
        'print-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/print-icon.svg'
        )
      )
      .addSvgIcon(
        'journal-edit-icon',
        sanitizer.bypassSecurityTrustResourceUrl(
          'assets/images/svg-icons/journal-edit-icon.svg'
        )
      );
  }
}
